import { RequiredOptions } from 'prettier';

export default {
	plugins: ['prettier-plugin-organize-attributes', '@ianvs/prettier-plugin-sort-imports'],
	trailingComma: 'es5',
	tabWidth: 2,
	singleQuote: true,
	useTabs: true,
	printWidth: 120,
	htmlWhitespaceSensitivity: 'ignore',
	arrowParens: 'avoid',
	quoteProps: 'preserve',
	attributeSort: 'ASC',
	attributeGroups: [
		'$ANGULAR_STRUCTURAL_DIRECTIVE',
		'$ANGULAR_ANIMATION',
		'$ANGULAR_ANIMATION_INPUT',
		'$ANGULAR_ELEMENT_REF',
		'^btn',
		'^link',
		'$ID',
		'$CLASS',
		'^i18n-alt',
		'^alt',
		'^i18n-label',
		'^label',
		'^i18n-placeholder',
		'^placeholder',
		'^i18n-title',
		'^title',
		'^i18n-tooltip',
		'^tooltip',
		'$DEFAULT',
		'^[\\[(?!\\(|@|attr\\.data-)]',
		'$ANGULAR_TWO_WAY_BINDING',
		'$ANGULAR_OUTPUT',
		'^[\\[attr\\.data-]',
		'^data-',
	],
	importOrderParserPlugins: ['typescript', 'classProperties', 'decorators-legacy'],
	importOrderTypeScriptVersion: '5.0.0',
	importOrder: [
		'^@ngneat/spectator$',
		'^ng-mocks$',
		'^@angular/core/?.*$',
		'<THIRD_PARTY_MODULES>',
		'',
		'^@global/(.*)$',
		'^@env/(.*)$',
		'',
		'^.*(\\.module)/?.*$',
		'',
		'^.*(\\.config)/?.*$',
		'',
		'^.*(/services|\\.service|/api|\\.api)/?.*$',
		'^.*(/guards|\\.guard)/?.*$',
		'',
		'^.*(/helpers|\\.helper)/?.*$',
		'',
		'^.*(/components|\\.component|/pages|/modals)/?.*$',
		'',
		'^.*(/directives|\\.directive)/?.*$',
		'',
		'^.*(/pipes|\\.pipe)/?.*$',
		'',
		'^.*(/testing|/mocks|\\.mock)/?.*$',
		'',
		'^.*(/interfaces|\\.interface|/loaders|\\.loader|/enums|\\.enum|/routes|\\.route|/model|\\.model|/classes)/?.*$',
		'',
		'^.*(/i18n|\\.i18n|/constants)/?.*$',
		'^[./]',
	],
	overrides: [
		{
			files: '*.html',
			options: {
				parser: 'angular',
			},
		},
	],
} as Partial<RequiredOptions>;
